resources:
  containers:
  - container: qarentena
    image: ernestosbarbosa/ruby-chromedriver:latest
    options: --user 0:0

trigger:
  - qarentena-azure-pipelines

pool:
  vmImage: 'ubuntu-latest'

container: qarentena

steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        sudo bundle install
        sudo bundle exec cucumber

  - task: PublishCucumberReport@1
    inputs:
      jsonDir: '$(System.DefaultWorkingDirectory)'
      outputPath: '$(Sytem.DefaultWorkingDirectory)'
      theme: 'bootstrap'
      reportSuiteAsScenarios: true
